/**
 * Deterministic AI prompt (generated by the backend from templates) — editable, copyable.
 * No image API is called; admins paste the prompt into their own tool.
 */
import { useState } from 'react'
import { ApiClientError } from '../../services/apiClient'

async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    const area = document.createElement('textarea')
    area.value = text
    area.setAttribute('readonly', '')
    area.style.position = 'fixed'
    area.style.opacity = '0'
    document.body.appendChild(area)
    area.select()
    const ok = document.execCommand('copy')
    area.remove()
    return ok
  }
}

export default function PromptPanel({ label = 'AI image prompt', generate, disabled = false, hint }) {
  const [text, setText] = useState('')
  const [family, setFamily] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  const run = async () => {
    setLoading(true)
    setError('')
    try {
      const result = await generate()
      setText(result.prompt)
      setFamily(result.family || '')
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : 'Could not build the prompt.')
    } finally {
      setLoading(false)
    }
  }

  const onCopy = async () => {
    if (await copyText(text)) {
      setError('')
      setCopied(true)
      setTimeout(() => setCopied(false), 1600)
    } else {
      setError('Copy failed — select the text and copy it manually.')
    }
  }

  return (
    <div className="border border-stone bg-white/60 p-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <span className="admin-label">
          {label}
          {family && <span className="ml-2 font-normal admin-muted">· {family.toLowerCase()} family</span>}
        </span>
        <div className="flex gap-2">
          <button
            type="button"
            className="admin-btn admin-btn-quiet px-3 py-1 text-[13px] disabled:opacity-50"
            onClick={run}
            disabled={disabled || loading}
          >
            {loading ? 'Building…' : text ? 'Regenerate' : 'Generate prompt'}
          </button>
          {text && (
            <button type="button" className="admin-btn px-3 py-1 text-[13px]" onClick={onCopy}>
              {copied ? 'Copied' : 'Copy'}
            </button>
          )}
        </div>
      </div>
      {hint && !text && <p className="mt-2 text-[12px] admin-muted">{hint}</p>}
      {text && (
        <textarea
          className="admin-input mt-2 min-h-[140px] font-mono text-[12.5px] leading-relaxed"
          value={text}
          onChange={(e) => setText(e.target.value)}
          aria-label={label}
        />
      )}
      {error && <p className="mt-2 text-[13px] text-burgundy">{error}</p>}
    </div>
  )
}
